spring.application.name=fleman-backend-full

spring.jackson.time-zone=Asia/Kolkata

# Active Profile
spring.profiles.active=dev

# JWT
app.jwt.secret=change-this-to-a-long-random-secret-before-any-real-deployment-32chars-min
app.jwt.expiration-ms=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GOOGLE_CLIENT_ID}
spring.mail.password=${GOOGLE_CLIENT_SECRET}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Google OAuth

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Actuator
management.endpoints.web.exposure.include=*


