// <auto-generated />
using System;
using FlemanApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlemanApi.Migrations
{
    [DbContext(typeof(FlemanDbContext))]
    partial class FlemanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlemanApi.Models.Addon", b =>
                {
                    b.Property<long>("AddonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AddonId"));

                    b.Property<string>("AddonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("DailyRate")
                        .HasColumnType("double");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly?>("RateValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RateValidTo")
                        .HasColumnType("date");

                    b.HasKey("AddonId");

                    b.HasIndex("AddonName")
                        .IsUnique();

                    b.ToTable("addons");
                });

            modelBuilder.Entity("FlemanApi.Models.Airport", b =>
                {
                    b.Property<long>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AirportId"));

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long>("HubId")
                        .HasColumnType("bigint");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("AirportId");

                    b.HasIndex("AirportCode")
                        .IsUnique();

                    b.ToTable("airports");
                });

            modelBuilder.Entity("FlemanApi.Models.BookingDetail", b =>
                {
                    b.Property<long>("BookingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BookingDetailId"));

                    b.Property<long>("AddonId")
                        .HasColumnType("bigint");

                    b.Property<double?>("AddonRate")
                        .HasColumnType("double");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("double");

                    b.HasKey("BookingDetailId");

                    b.ToTable("booking_details");
                });

            modelBuilder.Entity("FlemanApi.Models.BookingHeader", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<DateTime?>("ActualHandoverDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ActualReturnDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BookingStatus")
                        .HasColumnType("longtext");

                    b.Property<long?>("CarId")
                        .HasColumnType("bigint");

                    b.Property<long>("CarTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConfirmationNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("DropHubId")
                        .HasColumnType("bigint");

                    b.Property<double?>("EstimatedAmount")
                        .HasColumnType("double");

                    b.Property<int?>("HandoverFuelLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PickupHubId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReturnDatetime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BookingId");

                    b.HasIndex("ConfirmationNo")
                        .IsUnique();

                    b.ToTable("booking_headers");
                });

            modelBuilder.Entity("FlemanApi.Models.Car", b =>
                {
                    b.Property<long>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CarId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("CarTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("FuelLevel")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .HasColumnType("longtext");

                    b.Property<long>("HubId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<double?>("Mileage")
                        .HasColumnType("double");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Odometer")
                        .HasColumnType("int");

                    b.Property<int?>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CarId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("cars");
                });

            modelBuilder.Entity("FlemanApi.Models.CarType", b =>
                {
                    b.Property<long>("CarTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CarTypeId"));

                    b.Property<string>("CarTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("DailyRate")
                        .HasColumnType("double");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<double?>("MonthlyRate")
                        .HasColumnType("double");

                    b.Property<DateOnly?>("RateValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RateValidTo")
                        .HasColumnType("date");

                    b.Property<double?>("WeeklyRate")
                        .HasColumnType("double");

                    b.HasKey("CarTypeId");

                    b.HasIndex("CarTypeName")
                        .IsUnique();

                    b.ToTable("car_types");
                });

            modelBuilder.Entity("FlemanApi.Models.City", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("CityId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("FlemanApi.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DrivingLicenseNo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GovtIdDocument")
                        .HasColumnType("longtext")
                        .HasColumnName("govt_id_document");

                    b.Property<string>("GovtIdDocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("govt_id_document_name");

                    b.Property<string>("GovtIdDocumentType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("govt_id_document_type");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.HasIndex("DrivingLicenseNo")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("customers");
                });

            modelBuilder.Entity("FlemanApi.Models.Hub", b =>
                {
                    b.Property<long>("HubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("HubId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("HubId");

                    b.ToTable("hubs");
                });

            modelBuilder.Entity("FlemanApi.Models.InvoiceDetail", b =>
                {
                    b.Property<long>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InvoiceDetailId"));

                    b.Property<string>("AddonName")
                        .HasColumnType("longtext");

                    b.Property<double?>("AddonRate")
                        .HasColumnType("double");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("double");

                    b.HasKey("InvoiceDetailId");

                    b.ToTable("invoice_details");
                });

            modelBuilder.Entity("FlemanApi.Models.InvoiceHeader", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InvoiceId"));

                    b.Property<double?>("AddonAmount")
                        .HasColumnType("double");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("DamageNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Days")
                        .HasColumnType("int");

                    b.Property<long?>("DropHub")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<double?>("ExtraChargeAmount")
                        .HasColumnType("double");

                    b.Property<int?>("ExtraMiles")
                        .HasColumnType("int");

                    b.Property<double?>("FuelCharge")
                        .HasColumnType("double");

                    b.Property<DateTime?>("HandoverDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("HandoverFuelLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentType")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<long?>("PickupHub")
                        .HasColumnType("bigint");

                    b.Property<double?>("RentalAmount")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ReturnDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReturnFuelLevel")
                        .HasColumnType("int");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoice_headers");
                });

            modelBuilder.Entity("FlemanApi.Models.State", b =>
                {
                    b.Property<long>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StateId");

                    b.HasIndex("StateName")
                        .IsUnique();

                    b.ToTable("states");
                });
#pragma warning restore 612, 618
        }
    }
}
